rustler::atoms! {
    ok,
    error,
    invalid_index,
    invalid_coordinates,
    invalid_resolution,
    resolution_mismatch,
    compaction_failed,
    heterogeneous_resolution,
    duplicate_input,
    local_ij_error,
    invalid_string,
    dissolution_failed,
    not_neighbors,
    invalid_geometry,
}
